version: '3.8'

services:
  db-init:
    image: alpine:latest
    volumes:
      - ./fuckups.db:/fuckups.db
      - ./migrations:/migrations
    command: |
      sh -c "
        apk add --no-cache sqlite
        sqlite3 /fuckups.db < /migrations/20240101000000_create_fuckups_table.sql
        sqlite3 /fuckups.db < /migrations/20240101000001_add_likes_index.sql
        echo 'Database migrations completed'
      "
    profiles:
      - init

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fuckupboard-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./fuckups.db:/root/fuckups.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fuckupboard-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://fuckupboard-backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default
      - monitoring

networks:
  default:
    name: fuckupboard-network
  monitoring:
    external: true 
