global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend application
  - job_name: 'fuckupboard-frontend'
    static_configs:
      - targets: ['fuckupboard-frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Backend application
  - job_name: 'fuckupboard-backend'
    static_configs:
      - targets: ['fuckupboard-backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (if you want system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s 